name: face_attendance
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - cmake
  - openblas
  - lapack
  - pip:
    - numpy==1.26.4
    - pandas==2.1.4
    - opencv-python-headless==4.9.0.80
    - PySide6==6.6.1
    - mediapipe==0.10.9
    - dlib==19.24.2
    - face_recognition==1.3.0
    - openpyxl==3.1.2
