name: face_attendance
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.1.4
  - opencv=4.9.0
  - openpyxl=3.1.2
  - cmake
  - dlib
  - pip
  - pip:
    - PySide6==6.6.1
    - mediapipe==0.10.9
    - face_recognition==1.3.0
    - pyinstaller==6.3.0
